apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: kevinjnicholson/techtrends:latest
        name: techtrends
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }} 
            memory: {{ .Values.resources.limits.memory }}
        ports:
          - containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessprobe.path }}
            port: {{ .Values.livenessprobe.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessprobe.path }}
            port: {{ .Values.readinessprobe.containerPort }}
